apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800   # accesible en localhost:30800 con minikube/kind