apiVersion: v1
kind: ConfigMap
metadata:
  name: mancala-config
  namespace: default
data:
  OMP_NUM_THREADS: "4"
  MOTOR_PORT: "9000"
  MOTOR_TIMEOUT_S: "30"
  # En local el frontend está en NodePort 8080
  ALLOWED_ORIGINS: "http://localhost:8080"