apiVersion: v1
kind: Service
metadata:
  name: motor-svc
  namespace: default
spec:
  # ClusterIP: solo accesible dentro del clúster (desde el backend)
  type: ClusterIP
  selector:
    app: motor
  ports:
    - port: 9000
      targetPort: 9000